### ISSUE TITLE
java.util.ConcurrentModificationException on parallel execution of EVL/ETL/EOL when Enum value is used

### ISSUE THREAD

**Issue by robertcsakany** [eclipse-epsilon/epsilon#133]
`Caused by: org.eclipse.epsilon.eol.exceptions.EolInternalException: java.util.ConcurrentModificationException

	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
	at org.eclipse.epsilon.emc.emf.AbstractEmfModel.getEnumerationValue(AbstractEmfModel.java:156)
	at org.eclipse.epsilon.eol.models.ModelReference.getEnumerationValue(ModelReference.java:94)
	at org.eclipse.epsilon.eol.models.ModelRepository.getEnumerationValue(ModelRepository.java:200)
	at org.eclipse.epsilon.eol.dom.EnumerationLiteralExpression.execute(EnumerationLiteralExpression.java:34)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeImpl(ExecutorFactory.java:204)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.execute(ExecutorFactory.java:233)
	at org.eclipse.epsilon.eol.dom.EagerOperatorExpression.execute(EagerOperatorExpression.java:31)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeImpl(ExecutorFactory.java:204)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.execute(ExecutorFactory.java:233)
	at org.eclipse.epsilon.eol.dom.AndOperatorExpression.execute(AndOperatorExpression.java:34)
	at org.eclipse.epsilon.eol.dom.AndOperatorExpression.execute(AndOperatorExpression.java:1)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeImpl(ExecutorFactory.java:204)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.execute(ExecutorFactory.java:233)
	at org.eclipse.epsilon.eol.dom.AndOperatorExpression.execute(AndOperatorExpression.java:27)
	at org.eclipse.epsilon.eol.dom.AndOperatorExpression.execute(AndOperatorExpression.java:1)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeImpl(ExecutorFactory.java:204)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.execute(ExecutorFactory.java:233)
	at org.eclipse.epsilon.eol.dom.AndOperatorExpression.execute(AndOperatorExpression.java:27)
	at org.eclipse.epsilon.eol.dom.AndOperatorExpression.execute(AndOperatorExpression.java:1)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.executeImpl(ExecutorFactory.java:204)
	at org.eclipse.epsilon.eol.execute.ExecutorFactory.execute(ExecutorFactory.java:233)
	at org.eclipse.epsilon.eol.function.EolLambdaFactory.executeExpression(EolLambdaFactory.java:107)
	at org.eclipse.epsilon.eol.function.EolLambdaFactory.lambda$4(EolLambdaFactory.java:66)
	at org.eclipse.epsilon.eol.execute.operations.declarative.concurrent.ParallelSelectOperation.lambda$0(ParallelSelectOperation.java:51)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
	at org.eclipse.epsilon.eol.execute.concurrent.EolExecutorThread.run(EolExecutorThread.java:36)
Caused by: java.util.ConcurrentModificationException: null
`
Example:

`@cahced
operation JUDOPSM!TransferObjectType isGetRangeInputType() : Boolean {
    return JUDOPSM!TransferOperation.all()
        .exists(o | o.behaviour.isDefined() and o.behaviour.behaviourType == JUDOPSM!TransferOperationBehaviourType#GET_RANGE and
                    o.input.isDefined() and o.input.type == self);
}
`

It can be reproduced with any metamodel (3 of them have the same error)

EvlModuleParallelElements is used. When EvlModule it works fine.

**Comment by kolovos** [comment]
Thanks for reporting this. I've been able to reproduce the problem with [the attached minimal example](https://github.com/user-attachments/files/17608321/issue-113.zip) using both 2.5 and 2.6.

**Comment by agarciadom** [comment]
Thank you for the report. I'll have a look now.

**Comment by agarciadom** [comment]
Thank you for the report. I'll have a look now.

**Comment by agarciadom** [comment]
I tried adding this example to our the equivalence tests we use to compare parallel and non-parallel implementations of EVL, and I did not run into this error. When I compared the example from Dimitris with what our equivalence tests do, I noted that in concurrent environments, you should set the `concurrent` flag of the model to true, like this:

```java
model.setConcurrent(true);
```

This will instruct the model to use a number of concurrency-friendly data structures internally, which would impose unnecessary synchronisation overhead in a non-concurrent environment.

**Comment by agarciadom** [comment]
I have just pushed a number of tweaks to our documentation, indicating more clearly what has to be done when using multi-threaded implementations of the Epsilon languages from Java and from Ant:

https://eclipse.dev/epsilon/doc/articles/parallel-execution/

I'll close the issue as so far this seems to have been a gap in our documentation, but feel free to reopen if problems persist after adding `model.setConcurrent(true)` before you load your models.
