### ISSUE TITLE
Epsilon and 2024-12: problems with commonmark

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse-epsilon/epsilon#144]
After switching to 2024-12 (at least in the target platform), Epsilon picto has problem starting (e.g., when running another Eclipse instance or Plug-in JUnit tests), due to the commonmark package:

here's an example of the error reported (note that due to this, the Eclipse started takes more than 1 minute to start):

```
  Unresolved requirement: Require-Bundle: org.eclipse.epsilon.picto; bundle-version="2.3.0"; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.epsilon.picto; bundle-version="2.5.0.202404150823"; singleton:="true"
       org.eclipse.epsilon.picto [332]
         Unresolved requirement: Require-Bundle: org.eclipse.emf.emfatic.ui; resolution:="optional"
         Unresolved requirement: Require-Bundle: org.eclipse.gymnast.runtime.ui; resolution:="optional"
         Unresolved requirement: Require-Bundle: org.eclipse.emf.emfatic.core; resolution:="optional"
         Unresolved requirement: Require-Bundle: org.eclipse.gymnast.runtime.core; resolution:="optional"
  Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.eclipse.epsilon.picto [osgi.identity; type="osgi.bundle"; version:Version="2.5.0.202404150823"; osgi.identity="org.eclipse.epsilon.picto"; singleton:="true"] because it is exposed to package 'org.commonmark.renderer.html' from resources com.atlassian.commonmark [osgi.identity; type="osgi.bundle"; version:Version="0.15.1.v20200707-1444"; osgi.identity="com.atlassian.commonmark"] and org.commonmark [osgi.identity; type="osgi.bundle"; version:Version="0.24.0.v20241021-1700"; osgi.identity="org.commonmark"] via two dependency chains.

Chain 1:
  org.eclipse.epsilon.picto [osgi.identity; type="osgi.bundle"; version:Version="2.5.0.202404150823"; osgi.identity="org.eclipse.epsilon.picto"; singleton:="true"]
    require: (osgi.wiring.bundle=com.atlassian.commonmark)
     |
    provide: osgi.wiring.bundle: com.atlassian.commonmark
  com.atlassian.commonmark [osgi.identity; type="osgi.bundle"; version:Version="0.15.1.v20200707-1444"; osgi.identity="com.atlassian.commonmark"]

Chain 2:
  org.eclipse.epsilon.picto [osgi.identity; type="osgi.bundle"; version:Version="2.5.0.202404150823"; osgi.identity="org.eclipse.epsilon.picto"; singleton:="true"]
    require: (osgi.wiring.bundle=com.atlassian.commonmark-gfm-strikethrough)
     |
    provide: osgi.wiring.bundle; bundle-version:Version="0.15.1.v20200707-1444"; osgi.wiring.bundle="com.atlassian.commonmark-gfm-strikethrough"
  com.atlassian.commonmark-gfm-strikethrough [osgi.identity; type="osgi.bundle"; version:Version="0.15.1.v20200707-1444"; osgi.identity="com.atlassian.commonmark-gfm-strikethrough"]
    import: (osgi.wiring.package=org.commonmark.renderer.html)
     |
    export: osgi.wiring.package: org.commonmark.renderer.html
  org.commonmark [osgi.identity; type="osgi.bundle"; version:Version="0.24.0.v20241021-1700"; osgi.identity="org.commonmark"]
	at org.eclipse.osgi.container.Module.start(Module.java:493)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2102)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:143)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2093)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2033)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1996)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1912)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
```

I seem to understand that's due to both the bundles `com.atlassian.commonmark` and `org.commonmark` are installed. The former probably taken through a p2 reference to an old Orbit version (the Epsilon p2 site has site references) and the latter taken from the standard Eclipse 2024-12 p2 site (but also available in the 2024-12 Orbit).

**Comment by agarciadom** [comment]
Thank you for reporting this! I'll have a look at this now.

**Comment by agarciadom** [comment]
We have typically avoided Import-Package as it tends to be quite fragile in our experience. I was able to fix the problem by upgrading to the same CommonMark 0.24.0 release that is used in Eclipse 2024-12, getting it from the Orbit SimRel 2024-12 update site instead of that old Orbit site from 2021 (see the above #145 PR).

I have been able to start Eclipse 2024-12 from the Epsilon sources, and use the Markdown page of the `org.eclipse.epsilon.examples.picto.ecore` project without issues.

If you notice any new issues, please let us know. Thank you again for your report!

**Comment by LorenzoBettini** [comment]
@agarciadom thanks.

Will you do a new release as well?

**Comment by agarciadom** [comment]
We have another two issues listed for the 2.6.0 release at the moment:

https://github.com/eclipse-epsilon/epsilon/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.6.0

I'll have to check with the project lead if we want to wait until those are dealt with, or if we can postpone some of them to 2.7.0 and do a stable release for 2.6.0.

For the time being, you should be able to use the latest version of our interim update site, which should already have these corrections:

http://download.eclipse.org/epsilon/interim/

**Comment by agarciadom** [comment]
We have postponed those two issues to a future 2.7.0 release, and we are now preparing the 2.6.0 release.

**Comment by agarciadom** [comment]
We have published a new version (2.6). The update site is here:

http://download.eclipse.org/epsilon/updates/2.6/

We will post an announcement about this soon, but the full release notes are here:

https://projects.eclipse.org/projects/modeling.epsilon/releases/2.6/plan

**Comment by LorenzoBettini** [comment]
Thanks for fixing this.
